### PR TITLE
new mac version

### PR DESCRIPTION
**Pull request by jread-usgs**
```R
glm_version()
       ------------------------------------------------
       |  General Lake Model (GLM)   Version 2.1.6    |
       ------------------------------------------------
--help  : show this blurb
--nml <nmlfile> : get parameters from nmlfile
[1] 0
```

### CODE REVIEW

**Comment by jread-usgs** [comment]
@lawinslow what should the `GLMr` package version be? I'll let you take care of that if you want to change it.

**Comment by lawinslow** [comment]
Nice. I like this new UWA and USGS pipeline.

**Comment by jread-usgs** [comment]
:+1:

**Comment by lawinslow** [comment]
You can leave version as-is. Doesn't matter what it is, as long as it increases as we update things.

**Comment by lawinslow** [comment]
and I incremented it with the win version.

**Comment by jread-usgs** [comment]
seg fault on demo run:
```R
sim_folder <- run_example_sim(verbose = FALSE)
sh: line 1: 17120 Segmentation fault: 11  '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/GLMr/exec/macglm' > /dev/null 2> /dev/null
```
we are working on it. Keep this open.

**Comment by jread-usgs** [comment]
we should also probably try to figure out why this didn't get caught in the travis OSX build checks/tests

**Comment by jread-usgs** [comment]
wonder if we are having issues for win still: https://ci.appveyor.com/project/jread-usgs/glmtools/build/0.5.1.74#L284

**Comment by jread-usgs** [comment]
may just be the stuff I am doing w/ glmtools currently.

**Comment by lawinslow** [comment]
Ok, want to build and test for OS X the version that's now up? v2.1.7. Should fix the segfault issue.

**Comment by jread-usgs** [comment]
good to go @lawinslow

**Comment by lawinslow** [comment]
Awesome.

**Pull request merged**
